#!/bin/bash

# Pfad zur SSH-Konfigurationsdatei
SSH_CONFIG="/etc/ssh/sshd_config"

# Überprüfen, ob das Skript als root ausgeführt wird
if [ "$(id -u)" != "0" ]; then
   echo "Dieses Skript muss als root ausgeführt werden" 1>&2
   exit 1
fi

# Ändern der SSH-Konfigurationsdatei, um Passwort-Authentifizierung zu deaktivieren
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' $SSH_CONFIG

# Neustart des SSH-Dienstes, um die Änderungen wirksam zu machen
service ssh restart
